### ISSUE TITLE
3D Case Implementation

### ISSUE THREAD

**Issue by Sheepsody** [fab-jul/L3C-PyTorch#12]
Hi,

I'm currently working on Geometric Point Cloud Compression, and I'm really impressed by your approach. I have two questions I would like to ask you :
1. What do you think of the approach of Balle and al. ?
2. Do you have any recommendations for such an implementations ? I was thinking about a PointNet like structure.

Thanks a lot,
Have a nice week end!

**Comment by fab-jul** [comment]
We have never looked into point cloud compression. Balle et als. work focuses on lossy compression, while the paper behind this repo is proposing a lossless compression approach. The right way depends on your application.

**Comment by fab-jul** [comment]
I'll close this but feel free to reach out if you want to discuss further.
