### ISSUE TITLE
AssertionError: Expected a base dir for every component, got ['0524_0001'] and ['configs/ms', 'configs/dl']

### ISSUE THREAD

**Issue by zhaohui-yang** [fab-jul/L3C-PyTorch#15]
Thanks for sharing this great repo! 

I have cloned the repo and downloaded the pre-trained model. The pre-trained file was unzipped, and saved in 'root/src/log_dir/0524_0001/ckpts/ckpt_0000684250.pt'

As I ran the following code,
```
python test.py python test.py log_dir 0524_0001 ~/Data/kodak
```
I met the following error,

'AssertionError: Expected a base dir for every component, got ['0524_0001'] and ['configs/ms', 'configs/dl']'

I'm not sure if this is a personal question. Do you have any suggestions?

**Comment by fab-jul** [comment]
Hi, 

Some things:

- we updated the repo yesterday with new models! Please download and use these.
- is `log_dir` in the same folder as `test.py`? 
- what is the folder of the model called? If it's just `0524_0001`, that's not enough, it needs to have the configs there, e.g., `0524_0001 cr oi`.
- you wrote `python test.py python test.py` but I guess that's a typo?

**Comment by zhaohui-yang** [comment]
Thanks, bro! The reason is that I removed the 'cr oi' in the folder name. After fixing this problem, everything works fine!

**Comment by zhaohui-yang** [comment]
After using the following code to test the pre-trained model,

```
python test.py log_dir/ 0524_0001\ cr\ oi/ ~/Data/ImageNet/val/n07614500/ --names "L3C" --recursive=auto
```

the test phase works fine, but after that, an error occurred, the logs are as follow,

```
*** AC_NEEDS_CROP_DIM = 3000000
Testing 0524_0001 cr oi/ at -1 ---
Restoring log_dir/0524_0001 cr oi/ckpts/ckpt_0000684250.pt... (strict=True)
Testing Testset(n07614500): in /home/yangzhaohui/Data/ImageNet/val/n07614500, 50 images
0524_0001: ILSVRC2012_val_00049832 (        49): mean bpsp=4.643271541595459 crops:freq -> 1:500
0524_0001: ILSVRC2012_val_00049832 (        49): mean bpsp=4.643271541595459 crops:freq -> 1:50
*** Summary:
Testset   Experiment   Itr   Result
Traceback (most recent call last):
  File "test.py", line 141, in <module>
    main()
  File "test.py", line 137, in main
    a.append(testset.id,  names_to_log_date[log_date], str(restore_itr), result)
KeyError: '0524_0001'
```

Do you have any suggestions about this?

**Comment by fab-jul** [comment]
Looks like a bug in my code, but you can try running `test.py` without the `--names` flag. Also, you should only pass the log id:

```
python test.py log_dir/ 0524_0001 ~/Data/ImageNet/val/n07614500/ --recursive=auto
```

**Comment by zhaohui-yang** [comment]
Thanks, your code does not have bugs, the folder name in args should be 0524_0001.

By the way, is there any code to output the compressed images under different bpps while testing?

**Comment by fab-jul** [comment]
I'm not sure I understand, it's lossless compression :) the compressed image is the same as the input, always.

**Comment by zhaohui-yang** [comment]
Yes, I immediately realized I have asked a stupid question after typing it down.

**Comment by asfdhjfdjfagdahgj** [comment]
Thanks for sharing this great repo!
I also met the trouble 
AssertionError: Expected a base dir for every component, got ['1109_1715'] and ['configs/ms', 'configs/dl']
so I guess the trouble is in the ['configs/ms', 'configs/dl']
I found  the the code used the path of train_oi_r , but I cannot find it in the file. Do you have any suggestions?
