### ISSUE TITLE
questions about the probability prediction part in the paper

### ISSUE THREAD

**Issue by yaoqi-zd** [fab-jul/L3C-PyTorch#17]
Hi, thanks a lot for your work. I have two questions about the probalibity prediction part of your method:

1) L3C predicts a different conditional probability distribution p(x|f) for each image x and uses p to perform entropy encoding, am I right?

2) If I understand right about 1), the more accurate the estimated distribution p is, the smaller code length we can get after entropy encoding, so how about counting the number of different pixel values across each input image x, and normalize the counting results to get the probability distribution p' of x over pixel values, then we can also use p' for entropy encoding. What's the advantage of L3C over such method?

Thanks in advance for your reply!

**Comment by fab-jul** [comment]
Hi, thanks for your interest!
Re. 1: Yes, that's correct
Re. 2: That would also be a way, and is usually referred to as creating a histogram. The advantage of L3C is that the predicted `p` can vary locally. For example, in theory, the network can learn to predict a higher probability for green if it knows that it's predicting pixels in a tree.
