### ISSUE TITLE
What is the positional argument log_dir for?

### ISSUE THREAD

**Issue by sanjeetsahoo** [fab-jul/L3C-PyTorch#2]
I keep getting this I have a empty folder as log_dir, I am using the main model with id 0524_0001 and the images to be tested are in folder highres.
![Capture](https://user-images.githubusercontent.com/40137750/61620473-7cc30580-ac8e-11e9-8af4-76b7ed059c56.PNG)

**Comment by wensihan** [comment]
Hello,

The log_dir here means the directory where you save the 0524_0001. Such as home/Image Compression/0524_0001, the log_dir should be home/Image Compression. (If you cd to Image Compression, it can be ./)

Hope to help you.

**Comment by sanjeetsahoo** [comment]
Could you tell me which is the log_dir directory in the src folder uploaded on Github?

**Comment by wensihan** [comment]
Have you ever download the model of 0524_0001? If you download this model, and put it in the directory of src. Then, the log_dir will be ./ (current directory). Because you need to cd to the src to run the test.py.

**Comment by sanjeetsahoo** [comment]
I have downloaded the model with the name L3C.tar.gz from which I extracted the checkpoint file and put in a folder log_dir in my current directory and when I run the code below I get a error that ther is __main in the log_dir directory
![Capture_!](https://user-images.githubusercontent.com/40137750/61702886-2a511a00-ad5e-11e9-960c-56323ae51ceb.PNG)
![Capture_1](https://user-images.githubusercontent.com/40137750/61702887-2a511a00-ad5e-11e9-9080-3d1b6fb2b12e.PNG)

**Comment by wensihan** [comment]
You forgot test.py.


| |
温思寒
|
|
邮箱：chengyissing@163.com
|

签名由 网易邮箱大师 定制

On 07/23/2019 17:56, sanjeetsahoo wrote:

I have downloaded the model with the name L3C.tar.gz from which I extracted the checkpoint file and put in a folder log_dir in my current directory and when I run the code below I get a error that ther is __main in the log_dir directory

**Comment by sanjeetsahoo** [comment]
![Capture_3](https://user-images.githubusercontent.com/40137750/61703616-98e2a780-ad5f-11e9-96ad-bdca959bedff.PNG)
Sorry for the noob mistake above. But I am still getting the same old error

**Comment by wensihan** [comment]
Then, have you ever change the name of 0524_0001? 
For example:
(pytorch) [wency@localhost src]$ python test.py log_dir 0524_0001 /data/wency/kodak

The path of test.py: /home/wency/L3C/src/test.py
The path of 0524_0001: /home/wency/L3C/src/log_dir/0524_0001
And, the 0524_0001 contains: ckpts/ckpt_0000684250.pt

You can have a check, I think it still the problem of path.

Hope to help you.

**Comment by sanjeetsahoo** [comment]
Thank you very much for your constant help. It worked.
