### ISSUE TITLE
get errors when compress image

### ISSUE THREAD

**Issue by lfxx** [fab-jul/L3C-PyTorch#21]
use command below:
`python l3c.py --device=cpu /home/tt/workspace/L3C-PyTorch/logs 0306_0001 enc /home/longmao/workspace/L3C-PyTorch/2.png out1.l3c`
*** AC_NEEDS_CROP_DIM = 3000000
Status: torchac-backend-gpu available: False // torchac-backend-cpu available: True // CUDA available: True
*** Using torchac-backend-cpu; did set CUDA_AVAILABLE=False and DEVICE=cpu
Testing 0306_0001 at -1 ---
Restoring /home/tt/workspace/L3C-PyTorch/logs/0306_0001 cr oi/ckpts/ckpt_0001002750.pt... (strict=True)
*** WARN: Will discard 4th (alpha) channel.
Killed

**Comment by fab-jul** [comment]
hm what kind of image is this you are trying to encode? maybe it's too big? did you try
```
AC_NEEDS_CROP_DIM=100000 python l3c.py --device=cpu /home/tt/workspace/L3C-PyTorch/logs 0306_0001 enc /home/longmao/workspace/L3C-PyTorch/2.png out1.l3c
```
or an even lower number?

**Comment by fab-jul** [comment]
Will close this due to a lack of activity, please feel free to open with more details.
