### ISSUE TITLE
Question about CDF function and AC code

### ISSUE THREAD

**Issue by june1819** [fab-jul/L3C-PyTorch#25]
Hi
I don't understand how the program encode symbols with cdf function using AC code, if without PMF function. can you give me example about encoding?

Thank you

**Comment by fab-jul** [comment]
You mean the last layer of symbols, z_3? There, we just assume that they follow a uniform distribution, so each symbol has the same probabiliy 1/L (if we have L symbols). Let me know if you have further questions.

**Comment by june1819** [comment]
This function Cl(z|µ, σ) = sigmoid((z - µ)/σ) is equal to p(z(2)|f(3)) if s=2. the function C(z(s)
cuv|f(s+1)) is equal to sum p(z(s)|f(s+1))? am I right?
if I am right, the AC code can encode z(s) with it's prosibility of p(z(s)|f(s+1))?
