### ISSUE TITLE
GPU encoding/decoding entails errors

### ISSUE THREAD

**Issue by ChipsSpectre** [fab-jul/L3C-PyTorch#7]
After fixing the cpu version on my setup, the GPU encoding/decoding is still not error-free.

I could verify that the test.py script works.

The only major difference between the scripts is the MultiscaleTester `l3c` argument,
so I assume this affects the results.

Edit: It is not the `l3c` argument. I build a standalone compression script based on the `test.py`, 
and successively remove parts not needed for compression.

**Comment by ChipsSpectre** [comment]
Fixed. The error came from the way how PyTorch handles randomness.
https://pytorch.org/docs/stable/notes/randomness.html
![grafik](https://user-images.githubusercontent.com/11499442/65382911-c02d0500-dd0d-11e9-88c6-1186245059a7.png)

**Comment by fab-jul** [comment]
That's so awesome! Thanks a lot!
